services:
  db:
    image: mongo
    hostname: mongo
    env_file:
      - /meower-data/db/.env
    networks:
      - meower
    ports:
      - target: 27017
        published: 27017
        mode: host

networks:
  meower:
    name: meower
    external: true