services:
  redis:
    image: redis
    hostname: redis
    restart: unless-stopped
    volumes:
      - /meower-data/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - meower
    ports:
      - target: 6379
        published: 6379
        mode: host

networks:
  meower:
    name: meower
    external: true