services:
  uploads:
    image: ghcr.io/meower-media/uploads:latest
    hostname: uploads
    volumes:
      - /meower-data/uploads/.env:/app/.env:ro
      - /meower-data/uploads/ingest:/app/ingest  # tmpfs for good performance
    networks:
      - meower

networks:
  meower:
    name: meower
    external: true